### ISSUE TITLE
fps drops and prediction

### ISSUE THREAD

**Issue by sfcbk** [bckd00r/LViewPlus#11]
First thing first, I would like to thank you for sharing this with us. However, I'm having problems as the title says. Is it a bit slower than the original lview? Because drawings and other things that is shown on the screen are laggy. Another problem is that I don't think this repo has prediction. I tested it with many champ but skills are cast at exactly enemy's last location. It doesn't lead. 
Again thanks a lot for the repo
Thanks in advance.

**Comment by Finndramere** [comment]
right click the process that is running on Taskmanager > Details > Winstealer.exe then set priority to High. It helps but its still delayed sadly.

**Comment by bckd00r** [comment]
You need to set the click speed on orbwalker.
