### ISSUE TITLE
Format problem

### ISSUE THREAD

**Issue by Konasiewicz** [bckd00r/LViewPlus#13]
i have only this one problem do you know how to fix it ?

![image](https://user-images.githubusercontent.com/84810307/122063938-fc14d180-cdf0-11eb-875e-c0fcc44e6f11.png)

**Comment by bckd00r** [comment]
that's not a problem

**Comment by Konasiewicz** [comment]
ok and i have one more question addon AIM its not working for me... i choose 1234 for qwer and press them but my champ doesnt use spells...

**Comment by mfbulut** [comment]
Click on champion  You have to select manually

**Comment by Konasiewicz** [comment]
can someone pls make WS irelia and cassio last hitting minions irelia from Q and cassio from E ?

**Comment by mfbulut** [comment]
If you know some python you can do it yourself. Probably no one gonna make this.

**Comment by Konasiewicz** [comment]
unfortunately i dont know python so no idea how to do it :(
