### ISSUE TITLE
Hile menüsünü göremiyorum

### ISSUE THREAD

**Issue by UlikGames** [bckd00r/LViewPlus#15]
İndirdim,
Download boost 1.75.0
Unarchive it in LView/boost
Go into LView/boost
Run bootstrap.bat
Run b2 --with-python link=shared toolset=msvc-14.1 address-model=32 variant=release
bunların hepsini yaptım daha sonra realease yerini değiştirip winstealer dosyasına getirip run ediyorum. Oyunu açıyorum ve oyunu buluyor. Ama menü gelmiyor bi türlü hatta oyuna geldiğimde .exe kapanıyor. tekrar açıyorrum oyun buluyor ve kapanyıor. biraz araştırdım pip upgrade etdim bazı pipleri install ettim ve şuan oyunu buluyo ama menu gelmiyor. Ofsettler hepsi güncel. Unknowncheatsde sordumda benim gibi sorunu olan yok. Discord ve s. varsa yardım ede bilir misiniz ? Çünkü 3 gündür kafayı yicem yoksa

**Comment by bckd00r** [comment]
you should read everything carefully also you didn't set the location from config file.

**Comment by UlikGames** [comment]
teşekkür ederim yardımınız için. peki https://github.com/dxzin/lviewscript burdaki scriptleri  config file ekledim from blitz import * değiştirip from winstealer import * yaptım ama hata alıyorum. bu configleri ekleme şansınız var mı ?

**Comment by bckd00r** [comment]
> teşekkür ederim yardımınız için. peki https://github.com/dxzin/lviewscript burdaki scriptleri config file ekledim from blitz import * değiştirip from winstealer import * yaptım ama hata alıyorum. bu configleri ekleme şansınız var mı ?

bunları ben yapmıştım, fakat bunları desteklemiyorum o yüzden kendiniz yazmayı deneyin ;)

**Comment by UlikGames** [comment]
teşekkür ederim, yapmaya çalışırım. Peki oyundan kopmalara göre increase click speed yazmışsınız. Onu nerden ayarlıyacaz ?
