### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by sfcbk** [bckd00r/LViewPlus#2]
I couldn't fix this problem. Actually I also had to remove some part like 'Include="winstealer.rc' in the code to be able to compile the source. I thought it might be the cause of the problem but I'm not sure. And second question is I did 'pip install black' but I don't know which '*.py' file has to be copied to the GameplayScripts and named 'python format.py'. If you can help me to fix these problems I will be glad. Thanks in advance.

**Comment by bckd00r** [comment]
open CMD as administrator and write this "pip install requests" and you not need to use formatter ;)
