### ISSUE TITLE
UI don't appear

### ISSUE THREAD

**Issue by mfbulut** [bckd00r/LViewPlus#4]
I cloned repistory
I extract boost to right folder
I selected Release x86
I istalled python 3.9.0
I use Formatter and Compailed 
Everything looks working but in game menu don't appear
I use borderless window mode in game pls help

**Comment by bckd00r** [comment]
Offsetleri güncellememişsiniz, yeni bir sürüm paylaşmayacağım, reclass üzerinden offsetleri bulup kendiniz güncelleyebilirsiniz.
