### ISSUE TITLE
Game loses connection/after 3 seconds reconnected to game

### ISSUE THREAD

**Issue by unfair-tech** [bckd00r/LViewPlus#9]
edited: during spell trigger, will disconnect from the game, reconnecting 3~ seconds later

**Comment by unfair-tech** [comment]
also a hotkey to turn off menu would be dope

**Comment by Konasiewicz** [comment]
LEVRO#3213 can you contact me on discord?

**Comment by unfair-tech** [comment]
this issue isnt resolved however if u want more info feel free to dm
